import{createClient}from"https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const supabase=createClient("https://rnpoyzfimfngbzghcqmg.supabase.co","sb_publishable_OZlZvCj0U2Ih4QJZD-gDjw_TEYqCxyv");
const $=id=>document.getElementById(id);let products=[],categories=[],orders=[],settings=null;
const money=n=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(n)||0);
async function boot(){const{data:{session}}=await supabase.auth.getSession();if(session)await enter();else $("loginView").classList.remove("hidden")}
$("loginForm").onsubmit=async e=>{e.preventDefault();$("loginMsg").textContent="Signing in…";const{error}=await supabase.auth.signInWithPassword({email:$("email").value,password:$("password").value});if(error){$("loginMsg").textContent=error.message;return}await enter()};
async function enter(){const{data:ok,error}=await supabase.rpc("is_admin");if(error||!ok){await supabase.auth.signOut();$("loginMsg").textContent="This account is not authorized as an admin.";return}$("loginView").classList.add("hidden");$("appView").classList.remove("hidden");await loadAll();showTab("dashboard")}
$("logout").onclick=async()=>{await supabase.auth.signOut();location.reload()};
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
function showTab(t){document.querySelectorAll(".tab").forEach(x=>x.classList.add("hidden"));$(t).classList.remove("hidden");$("pageTitle").textContent=t==="dashboard"?"Overview":t.replace(/^./,x=>x.toUpperCase());if(t==="products")renderProducts();if(t==="categories")renderCategories();if(t==="orders")renderOrders();if(t==="settings")renderSettings()}
async function loadAll(){const[a,b,c,d]=await Promise.all([supabase.from("products").select("*").order("sort_order"),supabase.from("categories").select("*").order("sort_order"),supabase.from("orders").select("*").order("created_at",{ascending:false}).limit(100),supabase.from("business_settings").select("*").limit(1).maybeSingle()]);products=a.data||[];categories=b.data||[];orders=c.data||[];settings=d.data||null;renderDashboard();renderProducts();renderCategories();renderOrders();renderSettings()}
function renderDashboard(){$("stats").innerHTML=[["Products",products.length],["Available",products.filter(x=>x.is_available).length],["New orders",orders.filter(x=>x.status==="new").length],["Total orders",orders.length]].map(x=>'<div class="stat"><span>'+x[0]+'</span><strong>'+x[1]+"</strong></div>").join("");$("recentOrders").innerHTML=orders.slice(0,5).map(o=>'<div style="padding:12px 0;border-bottom:1px solid #e4e0d6"><strong>#'+o.id.slice(0,8)+'</strong> · '+esc(o.customer_name||"Customer")+' · '+money(o.total_amount)+' · <span class="status">'+o.status+"</span></div>").join("")||'<p class="muted">No orders yet.</p>'}
function renderProducts(){$("productTable").innerHTML='<table><thead><tr><th>Image</th><th>Product</th><th>Category</th><th>Price</th><th>Available</th><th>Actions</th></tr></thead><tbody>'+products.map(p=>'<tr><td><img class="thumb" src="'+(p.image_url||"")+'" onerror="this.style.visibility=\'hidden\'"></td><td><strong>'+esc(p.name)+'</strong><br><small>'+esc(p.description||"")+'</small></td><td>'+esc(cat(p.category_id))+'</td><td>'+money(p.price)+'</td><td>'+ (p.is_available?"Yes":"No")+'</td><td><div class="actions"><button data-edit="'+p.id+'">Edit</button><button data-toggle="'+p.id+'">'+(p.is_available?"Disable":"Enable")+'</button></div></td></tr>').join("")+'</tbody></table>';document.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>editProduct(b.dataset.edit));document.querySelectorAll("[data-toggle]").forEach(b=>b.onclick=()=>toggleProduct(b.dataset.toggle))}
function cat(id){return categories.find(x=>x.id===id)?.name||"—"}function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
$("addProduct").onclick=()=>openProduct();function openProduct(id=null){$("productDialog").classList.remove("hidden");$("productForm").reset();$("pId").value="";$("pAvailable").checked=true;$("pCategory").innerHTML=categories.map(c=>'<option value="'+c.id+'">'+esc(c.name)+"</option>").join("");$("productDialogTitle").textContent=id?"Edit product":"Add product";if(id){const p=products.find(x=>x.id===id);Object.assign($("pName"),{value:p.name});$("pCategory").value=p.category_id||"";$("pDescription").value=p.description||"";$("pIngredients").value=p.ingredients||"";$("pPrice").value=p.price;$("pSort").value=p.sort_order;$("pAvailable").checked=p.is_available;$("pId").value=p.id}}
$("productForm").onsubmit=async e=>{e.preventDefault();$("productMsg").textContent="Saving…";let id=$("pId").value;let imageUrl=null;const file=$("pImage").files[0];if(file){const ext=file.name.split(".").pop().toLowerCase(),path=crypto.randomUUID()+"."+ext;const up=await supabase.storage.from("product-images").upload(path,file,{upsert:false});if(up.error){$("productMsg").textContent=up.error.message;return}imageUrl=supabase.storage.from("product-images").getPublicUrl(path).data.publicUrl}const payload={name:$("pName").value.trim(),category_id:$("pCategory").value,description:$("pDescription").value.trim(),ingredients:$("pIngredients").value.trim(),price:Number($("pPrice").value),sort_order:Number($("pSort").value)||0,is_available:$("pAvailable").checked};if(imageUrl)payload.image_url=imageUrl;const r=id?await supabase.from("products").update(payload).eq("id",id):await supabase.from("products").insert(payload);if(r.error){$("productMsg").textContent=r.error.message;return}$("productDialog").classList.add("hidden");await loadAll()};
async function editProduct(id){openProduct(id)}async function toggleProduct(id){const p=products.find(x=>x.id===id);await supabase.from("products").update({is_available:!p.is_available}).eq("id",id);await loadAll()}
$("addCategory").onclick=()=>{$("categoryForm").reset();$("cId").value="";$("cActive").checked=true;$("categoryDialog").classList.remove("hidden")};
function renderCategories(){$("categoryTable").innerHTML='<table><thead><tr><th>Name</th><th>Order</th><th>Active</th><th>Actions</th></tr></thead><tbody>'+categories.map(c=>'<tr><td>'+esc(c.name)+'</td><td>'+c.sort_order+'</td><td>'+c.is_active+'</td><td><div class="actions"><button data-ce="'+c.id+'">Edit</button></div></td></tr>').join("")+'</tbody></table>';document.querySelectorAll("[data-ce]").forEach(b=>b.onclick=()=>{const c=categories.find(x=>x.id===b.dataset.ce);$("cId").value=c.id;$("cName").value=c.name;$("cSort").value=c.sort_order;$("cActive").checked=c.is_active;$("categoryDialog").classList.remove("hidden")})}
$("categoryForm").onsubmit=async e=>{e.preventDefault();const id=$("cId").value,p={name:$("cName").value.trim(),sort_order:Number($("cSort").value)||0,is_active:$("cActive").checked};const r=id?await supabase.from("categories").update(p).eq("id",id):await supabase.from("categories").insert(p);if(r.error){alert(r.error.message);return}$("categoryDialog").classList.add("hidden");await loadAll()};
function renderOrders(){$("ordersTable").innerHTML='<table><thead><tr><th>Order</th><th>Customer</th><th>Phone</th><th>Total</th><th>Status</th><th>Created</th></tr></thead><tbody>'+orders.map(o=>'<tr><td>#'+o.id.slice(0,8)+'</td><td>'+esc(o.customer_name||"")+'<br><small>'+esc(o.allergy_instructions||"")+'</small></td><td>'+esc(o.phone||"")+'</td><td>'+money(o.total_amount)+'</td><td><select data-status="'+o.id+'">'+["new","confirmed","preparing","ready","completed","cancelled"].map(s=>'<option '+(o.status===s?"selected":"")+'>'+s+"</option>").join("")+'</select></td><td>'+new Date(o.created_at).toLocaleString("en-IN")+'</td></tr>').join("")+'</tbody></table>';document.querySelectorAll("[data-status]").forEach(s=>s.onchange=async()=>{await supabase.from("orders").update({status:s.value}).eq("id",s.dataset.status);await loadAll()})}
$("refreshOrders").onclick=loadAll;
function renderSettings(){if(!settings)return;$("sBrand").value=settings.placeholder_brand_name||"";$("sPhone").value=settings.phone||"";$("sWhatsApp").value=settings.whatsapp||"";$("sInstagram").value=settings.instagram_url||"";$("sAddress").value=settings.address||"";$("sHours").value=settings.business_hours||""}
$("saveSettings").onclick=async()=>{const p={placeholder_brand_name:$("sBrand").value.trim(),phone:$("sPhone").value.trim(),whatsapp:$("sWhatsApp").value.trim(),instagram_url:$("sInstagram").value.trim(),address:$("sAddress").value.trim(),business_hours:$("sHours").value.trim()};const r=settings?await supabase.from("business_settings").update(p).eq("id",settings.id):await supabase.from("business_settings").insert(p);$("settingsMsg").textContent=r.error?r.error.message:"Saved.";await loadAll()};
document.querySelectorAll("[data-close]").forEach(x=>x.onclick=()=>$(x.dataset.close).classList.add("hidden"));boot();