import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
const supabase=createClient("https://rnpoyzfimfngbzghcqmg.supabase.co","sb_publishable_OZlZvCj0U2Ih4QJZD-gDjw_TEYqCxyv");
const fallback={"Mixed Seeds Laddu":"https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=1000&q=85","Nuts Laddu":"https://images.unsplash.com/photo-1490474418585-ba9bad8fd0ea?auto=format&fit=crop&w=1000&q=85","Mixed Seeds Pudding":"https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=1000&q=85","Nuts Pudding":"https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=1000&q=85","Seeds Mix Powder":"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=85","Nuts Mix Powder":"https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=1000&q=85"};
const state={products:[],categories:[],active:"all",cart:[],selected:null,qty:1},$=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(Number(n)||0);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const cat=id=>state.categories.find(x=>x.id===id)?.name||"Menu";
async function init(){const a=await Promise.all([supabase.from("business_settings").select("*").limit(1).maybeSingle(),supabase.from("categories").select("*").eq("is_active",true).order("sort_order"),supabase.from("products").select("*").eq("is_available",true).order("sort_order")]);const settings=a[0].data,cats=a[1].data||[],prods=a[2].data||[];if(a[2].error){$("products").innerHTML='<div class="loading-card"><p>Menu could not be loaded.</p></div>';return}state.categories=cats;state.products=prods;const brand=settings?.placeholder_brand_name||"Your Brand Name";$("brandName").textContent=brand;$("footerBrand").textContent=brand;document.title=brand;$("whatsappLink").href=settings?.whatsapp?"https://wa.me/"+settings.whatsapp.replace(/\D/g,""):"#";$("phoneLink").href=settings?.phone?"tel:"+settings.phone:"#";renderCats();renderProducts()}
function renderCats(){let h='<button class="'+(state.active==="all"?"active":"")+'" data-cat="all">All items</button>';state.categories.forEach(c=>h+='<button class="'+(state.active===c.id?"active":"")+'" data-cat="'+c.id+'">'+esc(c.name)+"</button>");$("categories").innerHTML=h;document.querySelectorAll("#categories button").forEach(b=>b.onclick=()=>{state.active=b.dataset.cat;renderCats();renderProducts()})}
function renderProducts(){const list=state.active==="all"?state.products:state.products.filter(p=>p.category_id===state.active);if(!list.length){$("products").innerHTML='<div class="loading-card"><p>No products are available right now.</p></div>';return}$("products").innerHTML=list.map(p=>{const img=p.image_url||fallback[p.name]||fallback["Mixed Seeds Laddu"];return '<article class="product-card" data-id="'+p.id+'"><div class="product-image" style="background-image:url(\''+img+'\')"><span class="product-badge">'+esc(cat(p.category_id))+'</span></div><div class="product-info"><h3>'+esc(p.name)+'</h3><p>'+esc(p.description||"Made with natural ingredients.")+'</p><div class="product-bottom"><span class="price">'+money(p.price)+'</span><button class="plus-button">+</button></div></div></article>'}).join("");document.querySelectorAll(".product-card").forEach(c=>c.onclick=()=>openProduct(c.dataset.id))}
function openProduct(id){const p=state.products.find(x=>x.id===id);if(!p)return;state.selected=p;state.qty=1;$("modalCategory").textContent=cat(p.category_id);$("modalName").textContent=p.name;$("modalDescription").textContent=p.description||"";$("modalIngredients").textContent=p.ingredients||"Natural ingredients";$("modalPrice").textContent=money(p.price);$("qtyValue").textContent="1";$("itemInstructions").value="";$("modalImage").style.backgroundImage="url('"+(p.image_url||fallback[p.name]||fallback["Mixed Seeds Laddu"])+"')";show("product")}
function show(t){$(t==="product"?"productModal":"cartModal").classList.remove("hidden");document.body.style.overflow="hidden"}function close(t){$(t==="product"?"productModal":"cartModal").classList.add("hidden");document.body.style.overflow=""}
document.querySelectorAll("[data-close]").forEach(x=>x.onclick=()=>close(x.dataset.close));
$("qtyMinus").onclick=()=>{state.qty=Math.max(1,state.qty-1);$("qtyValue").textContent=state.qty};$("qtyPlus").onclick=()=>{state.qty++;$("qtyValue").textContent=state.qty};
$("addToCart").onclick=()=>{const p=state.selected,n=$("itemInstructions").value.trim(),f=state.cart.find(x=>x.id===p.id&&x.note===n);if(f)f.qty+=state.qty;else state.cart.push({id:p.id,name:p.name,price:Number(p.price),qty:state.qty,note:n});updateCart();close("product")};
const total=()=>state.cart.reduce((s,x)=>s+x.qty*x.price,0);
function updateCart(){const c=state.cart.reduce((s,x)=>s+x.qty,0);$("cartCount").textContent=c+" item"+(c===1?"":"s");$("cartTotal").textContent=money(total());$("cartBar").classList.toggle("hidden",c===0)}
$("openCart").onclick=()=>{renderCart();show("cart")};
function renderCart(){$("cartItems").innerHTML=state.cart.length?state.cart.map((x,i)=>'<div class="cart-line"><div class="cart-line-main"><strong>'+esc(x.name)+'</strong><span>'+x.qty+" × "+money(x.price)+(x.note?" • "+esc(x.note):"")+'</span></div><div class="cart-line-actions"><button class="mini-button" data-minus="'+i+'">−</button><strong>'+x.qty+'</strong><button class="mini-button" data-plus="'+i+'">+</button></div></div>').join(""):'<p class="section-note">Your order is empty.</p>';$("checkoutTotal").textContent=money(total());document.querySelectorAll("[data-minus]").forEach(b=>b.onclick=()=>changeQty(+b.dataset.minus,-1));document.querySelectorAll("[data-plus]").forEach(b=>b.onclick=()=>changeQty(+b.dataset.plus,1))}
function changeQty(i,d){state.cart[i].qty+=d;if(state.cart[i].qty<=0)state.cart.splice(i,1);updateCart();renderCart()}
$("placeOrder").onclick=async()=>{const name=$("customerName").value.trim(),phone=$("customerPhone").value.trim(),instructions=$("orderInstructions").value.trim();if(!state.cart.length){$("orderMessage").textContent="Add something to your order first.";return}if(!name||phone.length<8){$("orderMessage").textContent="Please enter your name and a valid phone number.";return}$("placeOrder").disabled=true;$("orderMessage").textContent="Placing your order…";try{const {data:order,error}=await supabase.from("orders").insert({customer_name:name,phone,total_amount:total(),allergy_instructions:instructions}).select("id").single();if(error)throw error;const items=state.cart.map(x=>({order_id:order.id,product_id:x.id,product_name:x.name,unit_price:x.price,quantity:x.qty,item_instructions:x.note||null}));const r=await supabase.from("order_items").insert(items);if(r.error)throw r.error;state.cart=[];updateCart();renderCart();$("orderMessage").textContent="Order received. We'll contact you shortly."}catch(e){console.error(e);$("orderMessage").textContent="We couldn't place the order. Please try again."}$("placeOrder").disabled=false};
init();